# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-11 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_auto_20170811_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='faculty_question',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='program_question',
            field=models.CharField(default='yes', max_length=500),
        ),
    ]
