# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-21 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0005_profile_user_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='use_case',
            field=models.CharField(default='gym', max_length=500),
        ),
    ]
